news/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path

from .views import home
from .views import articoloDetailView
from .views import lista_articoli
from .views import queryBase
from .views import giornalistaDetailView
from .views import indexNews

app_name = "news"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('index_news', indexNews, name='index_news'),
    path('', home, name='homepage'), 
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", lista_articoli, name="lista_articoli"),
    path("lista_articoli/", lista_articoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
]

primo_progetto/urls.py
from django.contrib import admin
#admin rappresenta la sezione di amministrazione del sito.
#indichiamo il prefisso dei nostri url.
from django.urls import path,include
from .views import index_root


urlpatterns = [
    path('', index_root, name="index_root"),
    path('admin/', admin.site.urls),#admin rappresenta la sezione di amministrazione del sito. 
    path('prima_app/', include("prima_app.urls", namespace="prima_app")), #Questa riga include un altro file di configurazione URL
    path('seconda_app/',include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('news/',include("news.urls", namespace="news")),
    path('voti/',include("voti.urls", namespace="voti"))
]

news/models.py
from django.db import models

# Create your models here.
class Giornalista(models.Model):
    nome=models.CharField(max_length=20) #Stringhe di lunghezza massima 20
    cognome=models.CharField(max_length=20)
    anno_nascita=models.DateField(blank=True)
    #crea un id auto_increment 'nascosto' se non specificato
    
    def __str__(self):
        return self.nome + " " + self.cognome
    class Meta:
        verbose_name = 'Giornalista'
        verbose_name_plural = 'Giornalisti'

class Articolo(models.Model):
    visualizzazioni=models.IntegerField(default=0, blank=True)
    data_articolo=models.DateField(blank=True)
    #data_articolo=models.DateField(auto_now=True, blank=True)
    titolo=models.CharField(max_length=100) #Stringhe di lunghezza massima 100
    contenuto=models.TextField()
    giornalista=models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

    def __str__(self):
        return self.titolo
    
    class Meta:
        verbose_name = 'Articolo'
        verbose_name_plural = 'Articoli'

news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
import datetime

from .models import Articolo, Giornalista
 
# Create your views here.

#Versione 1: ritorna una pagina html con contenuto "HomePage news!"
'''
def home(request):
    return HttpResponse("<h1>HomePage news!</h1>")
'''

#Versione 2: legge dal database e li mette in stringhe di codice html 
'''
def home(request):
    a=""
    g=""
    for art in Articolo.objects.all(): #Articolo.objects.all() è una funzione che ritorna una lista di oggetti Articolo del database
        a+=(art.titolo + "<br>")
    
    for gio in Giornalista.objects.all(): #stessa cosa di Articolo.objects.all() 
        g+=(gio.nome + "<br>")
    response = "Articoli:<br>" + a + "<br>Giornalisti:<br>"+g
    print(response)
    return HttpResponse("<h1>"+ response + "</h1>")
'''

#Versione3: legge dal database e li mette in liste di stringhe
'''
def home(request):
    a = []
    g = []
    for art in Articolo.objects.all(): #Articolo.objects.all() è una funzione che ritorna una lista di oggetti Articolo del database
        a.append(art.titolo)

    for gio in Giornalista.objects.all(): #stessa cosa di Articolo.objects.all() 
        g.append(gio.nome)

    response = str(a) + "<br>" + str(g)

    return HttpResponse("<h1>"+ response + "</h1>")
'''

#Versione4: 
def home(request):
    articoli = Articolo.objects.all() #articoli è la lista di articoli letti dal database
    giornalisti = Giornalista.objects.all() #uguale a articoli

    #definisco un dizionario perchè la funzione render del return richiede per forza un dizionario
    context = {"articoli": articoli,
               "giornalisti": giornalisti}
    return render(request, "news/homepage.html", context)

def indexNews(request):
    return render(request, "news/index_news.html")

def articoloDetailView(request, pk):
    articolo = get_object_or_404(Articolo, pk=pk)
    context = {"articolo": articolo}
    return render(request, "news/articolo_detail.html", context)


def lista_articoli(request, pk=None):
    if(pk==None):
        intestazione="Tutti gli Articoli"
        articoli = Articolo.objects.all()
    else:
        intestazione="Articoli di un Giornalista"
        articoli = Articolo.objects.filter(giornalista_id=pk)
    context = {
        'intestazione': intestazione,
        'articoli': articoli,
    }
    return render(request, "news/lista_articoli.html", context)

'''
 quando non viene passato il parametro pk (primary key) del giornalista il suo valore sarà None
e quindi se pk==None utilizzerai  il metodo objects.all() altrimenti  il metodo objects.filter()
'''
def giornalistaDetailView(request, pk):
    giornalista = get_object_or_404(Giornalista, pk=pk)
    articoli_giornalista = Articolo.objects.filter(giornalista = giornalista)
    context = {"giornalista": giornalista,
               "articoli_giornalista" : articoli_giornalista}
    return render(request, "news/giornalista_detail.html", context)

def queryBase(request):
    #1. Tutti gli articoli scritti da giornalisti di un certo cognome:
    articoli_cognome = Articolo.objects.filter(giornalista__cognome='Rossi') #filter() ritorna una lista di oggetti, se non ci sono oggetti con cognome rossi, ritornerà una lista vuota
    
    #2. Totale
    numero_totale_articoli = Articolo.objects.count() #count() ritorna il numero di oggetti presenti nel db
    
    #3. Contare il numero di articoli scritti da un giornalista specifico:
    try:
        giornalista_1 = Giornalista.objects.get(id=2) # ritorna un oggetto con id=2, se non esiste va nel blocco except
        numero_articoli_giornalista_1 = Articolo.objects.filter(giornalista=giornalista_1).count()#conta la lunghezza della lista ritornata da filter()
    except Giornalista.DoesNotExist: #eccezione che può lanciare il metodo .get()
        numero_articoli_giornalista_1 = 0

    #4. Ordinare gli articoli per numero di visualizzazione in modo decrescente:
    articoli_ordinati = Articolo.objects.order_by('-visualizzazioni') #order_by() ordina i risultati, in questo caso mettendo il - davanti alla condizione li ordina in modo descrescente

    #5. Tutti gli articoli che non hanno visualizzazioni:
    articoli_senza_visualizzazioni = Articolo.objects.filter(visualizzazioni=0)

    #6. Articolo più visualizzato
    articolo_piu_visualizzato = Articolo.objects.order_by('-visualizzazioni').first()# first() Restituisce il primo elemento dell'order_by(-visualizzazioni).

    #7. Tutti i giornalisti nati dopo una certa data:
    giornalisti_data = Giornalista.objects.filter(anno_nascita__gt=datetime.date(1990, 1, 1))

    #8. Tutti gli articoli pubblicati in una data specifica
    articoli_del_giorno = Articolo.objects.filter(data_articolo=datetime.date(2023, 1, 1))

    #9. Tutti gli articoli pubblicati in un intervallo di date
    articoli_periodo = Articolo.objects.filter(data_articolo__range=(datetime.date(2023, 1, 1), datetime.date(2023, 12, 31)))

    #10. Gli articoli scritti da giornalisi nati prima del 1980:
    giornalisti_nati = Giornalista.objects.filter(anno_nascita__lt=datetime.date(1980, 1, 1))
    articoli_giornalisti = Articolo.objects.filter(giornalista__in=giornalisti_nati)

    #11. Il giornalista più giovane:
    giornalista_giovane = Giornalista.objects.order_by('anno_nascita').first()

    #12. Il giornalista più anziano:
    giornalista_anziano = Giornalista.objects.order_by('-anno_nascita').first()

    #13. Gli ultimi 5 articoli pubblicati:
    ultimi = Articolo.objects.order_by('-data_articolo')[:5] #[:5] limita il risultato ai primi 5

    #14. Tutti gli articoli con un certo numero minimo di visualizzazioni:
    articoli_minime_visualizzazioni = Articolo.objects.filter(visualizzazioni__gte=100)

    #15. Tutti gli articoli che contengono una certa parola nel titolo:
    articoli_parola = Articolo.objects.filter(titolo__icontains='importante')

    #16. Articoli pubblicati in un certo mese di un anno specifico
    articoli_mese_anno = Articolo.objects.filter(data_articolo__month=1, data_articolo__year=2023) #restituisce una lista

    #17. Giornalisti con almeno un articolo con più di 100 visualizzazioni
    giornalisti_con_articoli_popolari = Giornalista.objects.filter(articoli__visualizzazioni__gte=100).distinct

    data = datetime.date(1990,1,1)
    visualizzazioni = 50
    #18. Articoli sritti da giornalisti con anno_di_nascita>data e con le visualizzazioni>=50
    articoli_con_and = Articolo.objects.filter(giornalista__anno_nascita__gt=data, visualizzazioni__gte=visualizzazioni)

 
    from django.db.models import Q
    #19. articoli scritti da giornalisti con anno di nascita>data oppure visualizzazioni<=50
    articoli_con_or = Articolo.objects.filter(
        (Q(giornalista__anno_nascita__gt=data)) | Q(visualizzazioni__lte=visualizzazioni))
    
    #Per il not utilizzare l'operatore Q
    #20. articoli con not
    articoli_con_not = Articolo.objects.filter(~Q(giornalista__anno_nascita__lt=data)) #filtra su l'anno di nascita che deve essere maggiore o uguale a data
    
    articoli_con_not = Articolo.objects.exclude(giornalista__anno_nascita__lt=data)
    #exlude() che esclude gli articoli che soddisfano una determinata condizione.
    #quindi esclude gli articoli con anno_di_nascita<data
   

    #Dizionazio Contenxt
    context = {
        'articoli_cognome' : articoli_cognome,
        'numero_totale_articoli' : numero_totale_articoli,
        'numero_articoli_giornalista_1' : numero_articoli_giornalista_1,
        'articoli_ordinati' : articoli_ordinati,
        'articoli_senza_visualizzazioni' : articoli_senza_visualizzazioni,
        'articolo_piu_visualizzato' : articolo_piu_visualizzato,
        'giornalisti_data' : giornalisti_data,
        'articoli_del_giorno' : articoli_del_giorno,
        'articoli_periodo' : articoli_periodo,
        'articoli_giornalisti' : articoli_giornalisti,
        'giornalista_giovane' : giornalista_giovane,
        'giornalista_anziano' : giornalista_anziano,
        'ultimi' : ultimi,
        'articoli_minime_visualizzazioni' : articoli_minime_visualizzazioni,
        'articoli_parola' : articoli_parola,
        'articoli_mese_anno' : articoli_mese_anno,
        'giornalisti_con_articoli_popolari' : giornalisti_con_articoli_popolari,
        'articoli_con_and' : articoli_con_and,
        'articoli_con_or' : articoli_con_or,
        'articoli_con_not' : articoli_con_not
    }
    return render(request, 'news/query_base.html', context)

news/templates/news/articolo_detail.html
<!DOCTYPE html>
{% extends "base.html"%}

{%block title%} 
    {{ articolo.titolo }} 
{%endblock title%}

{%block content%}
   <h1>{{ articolo.titolo }}</h1>
   <h3>{{ articolo.contenuto }}</h3>
   <h5>Autore: <a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{ articolo.giornalista }}</a></h5>
{%endblock content%}

news/templates/news/giornalista_detail.html
<!DOCTYPE html>
{% extends "base.html"%}

{%block content%}
    <h1>Dettagli del giornalista: </h1>
    <h3>{{ giornalista.cognome }} {{ giornalista.nome }}</h1>
    <h3>nato il {{ giornalista.anno_nascita}}</h5>
    <h4>Tutti i suoi articoli e visualizzazioni </h4>
    {% if articoli_giornalista%}
        {% for articolo in articoli_giornalista%}
            <p><strong>- Titolo: </strong> <a href={% url 'news:articolo_detail' articolo.id %}>{{ articolo.titolo }}</a> ({{ articolo.visualizzazioni }} visualizzazioni) </p><!--articolo.id è la pk che viene richiesta nell'url 'articoli/<int:pk>'-->
        {% endfor %}
    {% else %}
        <p>Non ci sono elementi per il giornalista {{ giornalista.cognome }} {{ giornalista.nome }}
    {% endif %}
   


{%endblock content%}

news/templates/news/homepage.html
<!DOCTYPE html>
{% extends "base.html"%}

{%block title%} {{block.super}} | Articoli-Giornalisti {%endblock title%}

{%block content%}
    <h4>Articoli:</h4>
        {%for articolo in articoli %}
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    <h4>Giornalisti:</h4>
        {%for giornalista in giornalisti %}
            <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
            <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p>
            <hr>
        {% endfor %}
{%endblock content%}

news/templates/news/index_news.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Index News {% endblock title %}

{%block content%}
    <ol>
        <li><a href="{% url 'index_root'%}">Torna a index root</a></li> 
        <li><a href="{% url 'news:homepage'%}">Homepage benvenuto</a></li>
        <li><a href="{% url 'news:lista_articoli'%}">Lista Articoli</a></li>
        <li><a href="{% url 'news:query_base'%}">Query Base</a></li>
    </ol>
{% endblock content %}

news/templates/news/lista_articoli.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Lista-Articoli {% endblock title %}

{% block content %}
    <h4>{{ intestazione }}</h4>
        {% for articolo in articoli %}
            <p><strong>Titolo: </strong>
                <a href={% url 'news:articolo_detail' articolo.id %}>{{ articolo.titolo }}</a> <!--articolo.id è la pk che viene richiesta nell'url 'articoli/<int:pk>'-->
            </p>
            <p><strong>Contenuto: </strong>
                {{ articolo.contenuto }}
            </p>
            <p><strong>Autore: </strong>
                <a href={% url 'news:giornalista_detail' articolo.giornalista.id %}>{{ articolo.giornalista }}</a>
            </p>
            <hr>
        {% endfor %}
{% endblock content %}

news/templates/news/query_base.html
{% extends "base.html"%}

{% block title%}
    {{ block.super }} | Articoli e Giornalisti
{% endblock title%}

{% block content%}

    <h2>Articoli e statistiche</h2>

    <h4>1. Articoli scritti da giornalisti con un certo cognome</h4>
    {% if articoli_cognome %} <!--Se la lista non è vuota -->
        {% for articolo in articoli_cognome %}
            <p><strong>Id: </strong></p>
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}
    
    <hr>

    <h4>2. Numero totale di articoli</h4>
    <p>{{ numero_totale_articoli }}</p>
    <hr>

    <h4>3. Numero articoli del giornalista con ID = 2</h4>
    <p>{{ numero_articoli_giornalista_1 }}</p>
    <hr>

    <h4>4. Articoli ordinati per visualizzazioni (decrescente)</h4>
    {% if articoli_ordinati %} <!--Se la lista non è vuota -->
        {%for articolo in articoli %}
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}


    <hr>

    <h4>5. Articoli senza visualizzazioni</h4>
    {% if articoli_senza_visualizzazioni %} <!--Se la lista non è vuota -->
        {% for articolo in articoli_senza_visualizzazioni %}
            <p>{{ articolo.titolo }}</p>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}
    <hr>

    <h4>6. Articolo più visualizzato</h4>
        <p>
            {{ articolo_piu_visualizzato.titolo }}
            ({{ articolo_piu_visualizzato.visualizzazione }} visualizzazioni)
        </p>
    <hr>

    <h4>7. Giornalisti nati dopo il 1990</h4>
    {% if giornalisti_data %} <!--Se la lista non è vuota -->
        {% for giornalista in giornalisti_data %}
            <p>{{ giornalista.nome }} {{ giornalista.cognome }} ({{ giornalista.anno_di_nascita }})</p>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Giornalista presente</p>
    {% endif %}
    <hr>

    <h4>8. Articoli pubblicati il 01/01/2023</h4>
    {% if articoli_del_giorno %} <!--Se la lista non è vuota -->
        {% for articolo in articoli_del_giorno %}
            <p>{{ articolo.titolo }}</p>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}
    <hr>

    <h4>9. Articoli pubblicati nel 2023</h4>
    {% if articoli_periodo %} <!--Se la lista non è vuota -->
        {% for articolo in articoli_periodo %}
            <p>{{ articolo.titolo }} – {{ articolo.data }}</p>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}
    <hr>

    <h4>10. Articoli di giornalisti nati prima del 1980</h4>
    {% if articoli_giornalisti %} <!--Se la lista non è vuota -->
        {% for articolo in articoli_giornalisti_nati %}
            <p>{{ articolo.titolo }} – {{ articolo.giornalista }}</p>
        {% endfor %}
    {% else %} <!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}
    <hr>

    <h4>11. Giornalista più giovane</h4>
    <p>{{ giornalista_giovane.nome }} {{ giornalista_giovane.cognome }}</p>
    <hr>

    <h4>12. Giornalista più anziano</h4>
    {% if giornalista_anziano %}
        <p>{{ giornalista_anziano.nome }} {{ giornalista_anziano.cognome }}</p>
    {% endif %}
    <hr>

    <h4>13. Ultimi 5 articoli pubblicati</h4>
    {% for articolo in ultimi_5_articoli %}
        <p>{{ articolo.titolo }} – {{ articolo.data }}</p>
    {% endfor %}
    <hr>

    <h4>14. Articoli con almeno 100 visualizzazioni</h4>
    {% if articoli_minime_visualizzazioni%}
        {% for articolo in articoli_minime_visualizzazioni %}
            <p>{{ articolo.titolo }} ({{ articolo.visualizzazione }})</p>
        {% endfor %}
    {% else %}<!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}

    <hr>

    <h4>15. Articoli che contengono la parola "importante" nel titolo</h4>
    {% if articoli_parola%}
        {% for articolo in articoli_parola %}
            <p>{{ articolo.titolo }}</p>
        {% endfor %}
    {% else %}<!--La lista è vuota-->
        <p>Nessun Articolo presente</p>
    {% endif %}

    <h4>16. Articoli pubblicati in un certo mese di un anno specifico</h4>
    {%if articoli_mese_anno%}
        {% for articolo in articolo_mese_anno %}
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    {% else %}
        <p>Nessun Articolo presente</p>
    {% endif %}

    <h4>17. Giornalisti con almeno un articolo con più di 100 visualizzazioni</h4>
    {% if giornalisti_con_articoli_popolari%}
        {% for giornalista in giornalisti_con_articoli_popolari %}
            <p>{{ giornalista.nome }} {{ giornalista.cognome }} ({{ giornalista.anno_di_nascita }})</p>
            <hr>
        {% endfor %}
    {% else%}
        <p>Nessun Giornalista presente</p>
    {% endif%}

    <h4>18. Articoli con and</h4>
    {%if articoli_con_and%}
        {% for articolo in articoli_con_and %}
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    {% else %}
        <p>Nessun Articolo presente</p>
    {% endif %}

    <h4>19. Articoli con or</h4>
    {%if articoli_con_or%}
        {% for articolo in articoli_con_or %}
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    {% else %}
        <p>Nessun Articolo presente</p>
    {% endif %}

    <h4>20. Articoli con not </h4>
    {%if articoli_con_not%}
        {% for articolo in articoli_con_not %}
            <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
            <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
            <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
            <hr>
        {% endfor %}
    {% else %}
        <p>Nessun Articolo presente</p>
    {% endif %}


{% endblock content%}