news/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path

from .views import home
from .views import articoloDetailView
from .views import lista_articoli
from .views import queryBase
from .views import giornalistaDetailView
from .views import indexNews

app_name = "news"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('index_news', indexNews, name='index_news'),
    path('', home, name='homepage'), 
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", lista_articoli, name="lista_articoli"),
    path("lista_articoli/", lista_articoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
]

primo_progetto/urls.py
from django.contrib import admin
#admin rappresenta la sezione di amministrazione del sito.
#indichiamo il prefisso dei nostri url.
from django.urls import path,include
from .views import index_root


urlpatterns = [
    path('', index_root, name="index_root"),
    path('admin/', admin.site.urls),#admin rappresenta la sezione di amministrazione del sito. 
    path('prima_app/', include("prima_app.urls", namespace="prima_app")), #Questa riga include un altro file di configurazione URL
    path('seconda_app/',include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('news/',include("news.urls", namespace="news")),
    path('voti/',include("voti.urls", namespace="voti"))
]

prova_pratica_0/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path
#Importiamo la funzione es_if dal file views.py
from prova_pratica_0.views import indexProva
from prova_pratica_0.views import maxmin
from prova_pratica_0.views import media


app_name = "prova_pratica_0"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('', indexProva, name='view_a'), 
    path('maxmin', maxmin, name='maxmin'), 
    path('media', media, name='media'), 
]

prova_pratica_0/views.py
from django.shortcuts import render
import random

# Create your views here.
def indexProva(request):
      return render(request, "indexProva.html")

def maxmin(request):
      var1 = int(random.random()*10+1)
      var2 = int(random.random()*10+1)
      somma = var1+var2
      context = {
       'var1' : var1,
       'var2': var2, 
       'somma' : somma
    }
      return render(request, "maxmin.html", context)

def media(request):
      lista = []
      i = 0
      media = 0
      conta = 0
      for i in range(30):
         n = int(random.random()*10+1)
         media+=n
         lista.append(n)
         conta += 1 
      media = media/conta
      context = {
       'lista' : lista,
       'media' : media
    }
      return render(request, "media.html", context)

prova_pratica_0/templates/prova_pratica_0/indexProva.html
{%extends 'base.html'%}

{%block title%} {{block.super}} | Index Prova Pratica {%endblock title%}

{%block content%}
    <ol> 
        <!-- { % url “namespace:url” % }consente di inserire dinamicamente 
        un link senza doverlo scrivere noi. Si usa il namespace (app_name) 
        definito in primo_progetto/urls.py seguito dai due punti e poi 
        dal name dell’url definito in prima_app/urls.py-->
        <li><a href="{% url 'index_root'%}">Torna a index root</a></li> 
        <li><a href="{% url 'prova_pratica_0:maxmin'%}">Maxmin</a></li>
        <li><a href="{% url 'prova_pratica_0:media'%}">Media</a></li>
    </ol>
{%endblock content%}

prova_pratica_0/templates/prova_pratica_0/maxmin.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Max min {%endblock title%}

{%block content%}
    <b>var1 = {{ var1 }}</b> <br/>
    <b>var2 = {{ var2 }}</b> <br/>
    <b>somma = {{ somma }}

    {% if var1 > var2%}
      <p style="color: green">{{ var1 }}</p>
      <p style="color: red">{{ var2 }}</p>
    {% elif var2 > var1 %}
      <p style="color: green">{{ var2 }}</p>
      <p style="color: red">{{ var1 }}</p>
    {% endif %}

    {% if var1 == var2%}
    <p>I numeri sono uguali</p>
      <p style="color: black">{{ var1 }}</p>
      <p style="color: black">{{ var2 }}</p>
    {% endif %}
   
{%endblock content%}

prova_pratica_0/templates/prova_pratica_0/media.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Max min {%endblock title%}

{%block content%}
    
    <p>Media </p>
    {% for x in lista %}
      {% if x > 6%}
        <p style="color: green">{{ x }}</p>
      {% elif x < 6 %}
        <p style="color: red">{{ x }}</p>
      {% elif x == 6 %}
        <p style="color: black">{{ x }}</p>
      {% endif %}
    {% endfor %}
   
{%endblock content%}