news/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path

from .views import home
from .views import articoloDetailView
from .views import lista_articoli
from .views import queryBase
from .views import giornalistaDetailView
from .views import indexNews

app_name = "news"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('index_news', indexNews, name='index_news'),
    path('', home, name='homepage'), 
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", lista_articoli, name="lista_articoli"),
    path("lista_articoli/", lista_articoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
]

primo_progetto/urls.py
from django.contrib import admin
#admin rappresenta la sezione di amministrazione del sito.
#indichiamo il prefisso dei nostri url.
from django.urls import path,include
from .views import index_root


urlpatterns = [
    path('', index_root, name="index_root"),
    path('admin/', admin.site.urls),#admin rappresenta la sezione di amministrazione del sito. 
    path('prima_app/', include("prima_app.urls", namespace="prima_app")), #Questa riga include un altro file di configurazione URL
    path('seconda_app/',include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('news/',include("news.urls", namespace="news")),
    path('voti/',include("voti.urls", namespace="voti"))
]

voti/urls.py
from django.contrib import admin
#admin rappresenta la sezione di amministrazione del sito.
#indichiamo il prefisso dei nostri url.
from django.urls import path,include
from .views import index_voti
from .views import lista_materie
from .views import lista_voti
from .views import media_voti 
from .views import voto_max_min

app_name = 'voti'

urlpatterns = [
    path('', index_voti, name="index_voti"),
    path("lista_materie/", lista_materie, name="lista_materie"),
    path("lista_voti/", lista_voti, name="lista_voti"),
    path("media_voti/", media_voti, name="media_voti"),
    path("voto_max_min/", voto_max_min, name="voto_max_min"),
]

voti/models.py
from django.db import models

# Create your models here.

voti/views.py
from django.shortcuts import render

# Create your views here.
def index_voti(request):
    return render(request, 'voti/index_voti.html')

def lista_materie(request):
    materie = ["Matematica","Italiano","Inglese","Storia","Geografia"]
    context = {
        'materie' : materie
    }
    return render(request, 'voti/lista_materie.html', context)

def lista_voti(request):
    voti = {'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7,4),("Storia",7,4),("Geografia",5,7)],
           'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9,0),("Storia",8,2),("Geografia",8,1)],
           'Nicola Spina':[("Matematica",7,2),("Italiano",6,2),("Inglese",4,3),("Storia",8,2),("Geografia",8,2)]}
    context = { 
        'voti' : voti
    }
    return render(request, 'voti/lista_voti.html', context)

def media_voti(request):
    voti = {'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7,4),("Storia",7,4),("Geografia",5,7)],
           'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9,0),("Storia",8,2),("Geografia",8,1)],
           'Nicola Spina':[("Matematica",7,2),("Italiano",6,2),("Inglese",4,3),("Storia",8,2),("Geografia",8,2)]}

    media_voti = {}
    for studente, materie in voti.items():
        media = 0
        for materia,voto,assenze in materie:
            media+=voto
        media/=len(materie)
        media_voti[studente]=media
           
    context = { 
        'media_voti' : media_voti
    }
    return render(request, 'voti/media_voti.html', context)


# voti massimo e minimo, le materie in cui si sono registrati e gli studenti che li hanno ottenuti
def voto_max_min(request):
    
    voti = {'Giuseppe Gullo':[("Matematica",9,0),("Italiano",7,3),("Inglese",7,4),("Storia",7,4),("Geografia",5,7)],
           'Antonio Barbera':[("Matematica",8,1),("Italiano",6,1),("Inglese",9,0),("Storia",8,2),("Geografia",8,1)],
           'Nicola Spina':[("Matematica",7,2),("Italiano",6,2),("Inglese",4,3),("Storia",8,2),("Geografia",8,2)]}
    
    voto_max = 0
    voto_min = 11

    #trovo minimo e massimo
    for studente, materie in voti.items():
        for materia, voto, assenze in materie:
            if(voto>voto_max):
                voto_max=voto
            if(voto_min>voto):
                voto_min=voto

    studenti_max=[]
    studenti_min=[]
    materie_max=[]
    materie_min=[]

    for studente, materie in voti.items():
        for materia, voto, assenze in materie:
            if(voto_max==voto):
                studenti_max.append(studente)
                materie_max.append(materia)
            if(voto_min==voto):
                studenti_min.append(studente)
                materie_min.append(materia)

    max={
        'voto': voto_max,
        'studenti': studenti_max,
        'materie' : materie_max
    }
    min={
        'voto': voto_min,
        'studenti': studenti_min,
        'materie' : materie_min
    }

    context = {
        'min' : min,
        'max' : max
    }
    return render(request, 'voti/voto_max_min.html', context)

voti/templates/voti/index_voti.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Index Voti {% endblock title %}

{%block content%}
    <ol>
        <li><a href="{% url 'index_root'%}">Torna a index root</a></li> 
        <li><a href="{% url 'voti:lista_materie'%}">Lista Materie</a></li> 
        <li><a href="{% url 'voti:lista_voti'%}">Voti studenti</a></li> 
        <li><a href="{% url 'voti:media_voti'%}">Media studenti</a></li> 
        <li><a href="{% url 'voti:voto_max_min'%}">Max min voti</a></li> 
    </ol>
{% endblock content %}

voti/templates/voti/lista_materie.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Lista Materie {% endblock title %}

{%block content%}
    <h4>Lista materie</h4>
    <ul>
    {% for materia in materie%}
        <li>{{materia}}</li>
    {%endfor%}
    </ul>
{% endblock content %}

voti/templates/voti/lista_voti.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Lista Voti {% endblock title %}

{%block content%}
    <h4>Lista voti</h4>
    {% for studente,materie in voti.items%}
        <h5>{{studente}}</h5>
        {% for materia,voto,assenze in materie%}
            <p>{{materia}}, {{voto}}, {{assenze}}</p>
        {% endfor %}
    {% endfor %}
{% endblock content %}

voti/templates/voti/media_voti.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Media Voti {% endblock title %}

{%block content%}
    <h4>Media voti</h4>
    {% for studente,media in media_voti.items%}
        <h5>{{studente}}</h5>
        <p>{{media}}</p>
        <hr>
    {% endfor %}
{% endblock content %}

voti/templates/voti/voto_max_min.html
<!DOCTYPE html>
{% extends "base.html"%}

{% block title %} {{ block.super }} | Voti, materie, studenti {% endblock title %}

{%block content%}
    <h4>Voto massimo: {{ max.voto }}</h4>
    <p>Materie con voto massimo: {{ max.materie }} </p>
    <p>Studenti con voto massimo: {{ max.studenti }}</p>

    <br>
    
    <h4>Voto minimo: {{ min.voto }}</h4>
    <p>Materie con voto minimo: {{ min.materie }} </p>
    <p>Studenti con voto minimo: {{ min.studenti }}</p>

   
{% endblock content %}