news/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path

from .views import home
from .views import articoloDetailView
from .views import lista_articoli
from .views import queryBase
from .views import giornalistaDetailView
from .views import indexNews

app_name = "news"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('index_news', indexNews, name='index_news'),
    path('', home, name='homepage'), 
    path("articoli/<int:pk>", articoloDetailView, name="articolo_detail"),
    path("lista_articoli/<int:pk>", lista_articoli, name="lista_articoli"),
    path("lista_articoli/", lista_articoli, name="lista_articoli"),
    path("query_base/", queryBase, name="query_base"),
    path("giornalisti/<int:pk>", giornalistaDetailView, name="giornalista_detail"),
]

prima_app/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path
#Importiamo la funzione homepage dal file views.py
from prima_app.views import homepage
#Importiamo la funzione welcome dal file views.py
from prima_app.views import welcome
#Importiamo la funzione lista dal file views.py
from prima_app.views import lista
#Importiamo la funzione chisiamo dal file views.py
from prima_app.views import chi_siamo
#Importiamo la funzione variabili del file views.py
from prima_app.views import variabili
#Importiamo la funzione index del file views.py
from prima_app.views import index

app_name = "prima_app"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('index', index, name='index'), #http://localhost:8000/
    path('homepage', homepage, name='homepage'), #http://localhost:8000/homepage
    path('welcome', welcome, name='welcome'), #localhost:8000/welcome
    path('lista', lista, name="lista"), #localhost:8000/lista
    path('chi_siamo', chi_siamo, name="chi_siamo"), #localhost:8000/chi_siamo
    path('variabili', variabili, name='variabili'), #localhost:8000/variabili
]

primo_progetto/urls.py
from django.contrib import admin
#admin rappresenta la sezione di amministrazione del sito.
#indichiamo il prefisso dei nostri url.
from django.urls import path,include
from .views import index_root


urlpatterns = [
    path('', index_root, name="index_root"),
    path('admin/', admin.site.urls),#admin rappresenta la sezione di amministrazione del sito. 
    path('prima_app/', include("prima_app.urls", namespace="prima_app")), #Questa riga include un altro file di configurazione URL
    path('seconda_app/',include("seconda_app.urls", namespace="seconda_app")),
    path('prova_pratica_0/',include("prova_pratica_0.urls", namespace="prova_pratica_0")),
    path('news/',include("news.urls", namespace="news")),
    path('voti/',include("voti.urls", namespace="voti"))
]

prova_pratica_0/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path
#Importiamo la funzione es_if dal file views.py
from prova_pratica_0.views import indexProva
from prova_pratica_0.views import maxmin
from prova_pratica_0.views import media


app_name = "prova_pratica_0"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('', indexProva, name='view_a'), 
    path('maxmin', maxmin, name='maxmin'), 
    path('media', media, name='media'), 
]

seconda_app/urls.py
#Importiamo la funzione path da un modulo di django 
from django.urls import path
#Importiamo la funzione es_if dal file views.py
from seconda_app.views import es_if
#Importiamo la funzione if_else_elif dal file views.py
from seconda_app.views import if_else_elif
#Importiamo la funzione index_condizioni dal file views.py
from seconda_app.views import index_condizioni
#Importiamo la funzione es_for dal file views.py
from seconda_app.views import es_for


app_name = "seconda_app"
#Creiamo un vettore con tutti gli url della nostra applicazione.
urlpatterns = [
    #La funzione path definisce l’url
    #Il primo parametro rappresenta l’url(solo la parte dopo localhost:8000)
    # Il secondo parametro è la funzione da chiamare. 
    # Il terzo parametro è un nome che serve per identificare in modo univoco l’url nel server.
    path('index_condizioni', index_condizioni, name='index_condizioni'),
    path('es_if', es_if, name='es_if'),
    path('if_else_elif.html', if_else_elif, name='if_else_elif'),
    path('es_for.html', es_for, name='es_for')
]

voti/urls.py
from django.contrib import admin
#admin rappresenta la sezione di amministrazione del sito.
#indichiamo il prefisso dei nostri url.
from django.urls import path,include
from .views import index_voti
from .views import lista_materie
from .views import lista_voti
from .views import media_voti 
from .views import voto_max_min

app_name = 'voti'

urlpatterns = [
    path('', index_voti, name="index_voti"),
    path("lista_materie/", lista_materie, name="lista_materie"),
    path("lista_voti/", lista_voti, name="lista_voti"),
    path("media_voti/", media_voti, name="media_voti"),
    path("voto_max_min/", voto_max_min, name="voto_max_min"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{%block title%} Primo progetto {%endblock title%}</title>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</head>

<body>
    <!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Primo Progetto</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prima app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Homepage benvenuto</a>
          <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
          <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
          <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
          <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
        </div>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Seconda app
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Esercizio if</a>
          <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">Esercizio if/else/elif</a>
          <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Esercizio for</a>
        </div>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Prova pratica 
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'prova_pratica_0:view_a'%}">Index Prova</a>
        </div>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          News
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'news:homepage'%}">Homepage</a>
          <a class="dropdown-item" href="{% url 'news:lista_articoli'%}">Lista Articoli</a>
          <a class="dropdown-item" href="{% url 'news:query_base'%}">Query</a>
        </div>
      </li>


    </ul>
  </div>
</nav>

    {%block content%}
    {%endblock content%}
    
    {%block script%}
    {%endblock script%}
</body>

</html>

templates/index_root.html
{% extends "base.html"%}

{%block title%} {{block.super}} | Index root {%endblock title%}

{%block content%}
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">Index prima app</a></li>
        <li><a href="{% url 'seconda_app:index_condizioni'%}">Index seconda app</a></li>
        <li><a href="{% url 'news:index_news'%}">Index news</a></li>
        <li><a href="{% url 'voti:index_voti'%}">Index voti</a></li>
    </ol>
{%endblock content%}